user nginx;
worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout 65;
    client_max_body_size 200M;

    server {
        listen 80;
        server_name localhost;

        location / {
            proxy_pass http://backend:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # Отключаем кэш в локальной разработке
            add_header Cache-Control "no-store, no-cache, must-revalidate";
            proxy_no_cache 1;
            proxy_cache_bypass 1;
        }

        location /static/ {
            alias /var/www/static/;
            expires off;
            access_log off;
            add_header Cache-Control "no-store";
        }

        location /media/ {
            alias /app/media/;
            expires off;
            access_log off;
            add_header Content-Disposition 'inline';
            types {
                application/pdf pdf;
                application/vnd.openxmlformats-officedocument.wordprocessingml.document docx;
                application/msword doc;
                image/jpeg jpg jpeg;
                image/png png;
                image/webp webp;
                image/gif gif;
                image/svg+xml svg;
            }
            default_type application/octet-stream;
        }

        types {
            text/css css;
            application/javascript js;
            image/svg+xml svg svgz;
            image/x-icon ico;
        }
    }
}
