# Generated by Django 5.2.7 on 2026-09-21 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Загрузите изображение товара акции', upload_to='action_products/', verbose_name='Изображение товара')),
                ('name', models.CharField(max_length=200, verbose_name='Название товара')),
                ('description', models.TextField(help_text='Подробное описание товара-участника акции', verbose_name='Описание товара')),
                ('link', models.URLField(blank=True, help_text='Опциональная ссылка на страницу товара', null=True, verbose_name='Ссылка на товар')),
                ('show_in_products_block', models.BooleanField(default=False, help_text='Товар попадёт в статичный блок из 8 карточек на десктопе', verbose_name='Показывать в блоке «Товары-участники» (десктоп)')),
                ('products_block_order', models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем раньше товар показывается в блоке на десктопе', verbose_name='Порядок в блоке «Товары-участники»')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Акционный товар',
                'verbose_name_plural': 'Акционные товары',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например, "Белгород"', max_length=60, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(default='ООО «ЧНГ»', max_length=255, verbose_name='Название организации')),
                ('customer_name', models.CharField(default='АО «Птицефабрика «Атемарская»', help_text='Если отличается от организатора акции (бриф, п. 1).', max_length=255, verbose_name='Заказчик работ')),
                ('brand_name', models.CharField(default='Атемарская Ферма', help_text='Бренд, от имени которого идёт акция.', max_length=255, verbose_name='Торговая марка')),
                ('promotion_name', models.CharField(default='Купи и выиграй с Атемарской', max_length=255, verbose_name='Название акции')),
                ('landing_url', models.CharField(default='https://af-promo.ru', help_text='Лендинг живёт на отдельном домене, личный кабинет ссылается на него.', max_length=255, verbose_name='Адрес лендинга')),
                ('cheqly_link', models.CharField(default='cheqly.ru', max_length=255, verbose_name='Ссылка на CheqLy')),
                ('footer_text', models.TextField(default='Срок проведения акции с 1 октября 2026 года по 31 января 2027 года. Период совершения покупки и регистрации чеков — с 1 октября 2026 года по 10 января 2027 года. Внешний вид призов может отличаться от изображений в рекламных материалах. Информацию об Организаторе акции, о правилах её проведения, количестве призов, сроке, месте и порядке их получения можно узнать на сайте af-promo.ru', verbose_name='Текст в футере')),
                ('privacy_policy', models.FileField(blank=True, null=True, upload_to='personal_data/', verbose_name='Обработка персональных данных')),
                ('personal_data_consent', models.FileField(blank=True, null=True, upload_to='personal_data_consent/', verbose_name='Согласие на обработку персональных данных')),
                ('rules', models.FileField(blank=True, null=True, upload_to='rules/', verbose_name='Правила акции')),
                ('products_list', models.FileField(blank=True, null=True, upload_to='', verbose_name='Файл со всеми товарами')),
                ('email', models.EmailField(default='af@cheqly.ru', help_text='Для обратной связи от клиентов', max_length=50, verbose_name='Email')),
                ('legal_address', models.CharField(blank=True, default='', max_length=255, verbose_name='Юридический адрес')),
                ('inn', models.CharField(blank=True, default='', max_length=20, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, default='', max_length=20, verbose_name='КПП')),
                ('settlement_account', models.CharField(blank=True, default='', max_length=30, verbose_name='Расчётный счёт (р/с)')),
                ('correspondent_account', models.CharField(blank=True, default='', max_length=30, verbose_name='Корреспондентский счёт (к/с)')),
                ('bik', models.CharField(blank=True, default='', max_length=20, verbose_name='БИК')),
                ('bank_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Наименование банка')),
                ('ogrn', models.CharField(blank=True, default='', max_length=20, verbose_name='ОГРН')),
                ('seo_production_mode', models.BooleanField(default=False, help_text='Выключено — сайт ещё не индексируется: sitemap.xml недоступен, ссылка на него в robots.txt закомментирована (состояние "до начала акции"). Включите перед стартом акции — sitemap.xml заработает, а в robots.txt раскомментируется ссылка на него.', verbose_name='Боевой режим SEO (robots.txt и sitemap.xml)')),
            ],
            options={
                'verbose_name': 'Информация о компании',
                'verbose_name_plural': 'Информация о компании',
            },
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('hero', 'Первый экран'), ('how_to_participate', 'Как участвовать'), ('instant_prizes', 'Моментальные призы'), ('weekly_prizes', 'Еженедельные призы'), ('monthly_prizes', 'Ежемесячные призы'), ('main_prize', 'Главный приз'), ('products', 'Товары акции'), ('winners', 'Победители'), ('rules', 'Условия участия'), ('faq', 'Вопросы и ответы'), ('documents', 'Документы'), ('contacts', 'Контакты')], max_length=50, unique=True, verbose_name='Секция')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=500, verbose_name='Подзаголовок')),
                ('body', models.TextField(blank=True, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='content/', verbose_name='Изображение')),
                ('is_visible', models.BooleanField(default=True, help_text='Снятая галочка убирает секцию с лендинга — удалять её из шаблона не нужно.', verbose_name='Показывать')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Блок главной страницы',
                'verbose_name_plural': 'Блоки главной страницы',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='Вопрос')),
                ('answer', models.TextField(max_length=1000, verbose_name='Ответ')),
                ('order', models.PositiveIntegerField(default=1, help_text='Порядок отображения', verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Вопрос-ответ',
                'verbose_name_plural': 'Вопросы-ответы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MomentPrizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Загрузите изображение моментального приза', upload_to='moment_prizes/', verbose_name='Изображение')),
                ('name', models.CharField(help_text='Краткое название приза', max_length=100, verbose_name='Название приза')),
                ('caption', models.CharField(help_text='Дополнительный текст под изображением', max_length=255, verbose_name='Подпись')),
                ('order', models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем выше в списке', verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Моментальный приз',
                'verbose_name_plural': 'Моментальные призы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MonthPrizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Загрузите изображение приза месяца', upload_to='month_prizes/', verbose_name='Изображение')),
                ('name', models.CharField(help_text='Краткое название приза', max_length=100, verbose_name='Название приза')),
                ('caption', models.CharField(help_text='Дополнительный текст под изображением', max_length=255, verbose_name='Подпись')),
                ('order', models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем выше в списке', verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Ежемесячный приз',
                'verbose_name_plural': 'Ежемесячные призы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ParticipationStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Номер шага')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, verbose_name='Описание')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='content/steps/', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Шаг участия',
                'verbose_name_plural': 'Шаги участия',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='SEOSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Купи и выиграй с Атемарской', help_text='Используется, если у страницы не задан свой заголовок', max_length=255, verbose_name='Заголовок по умолчанию (title)')),
                ('description', models.TextField(default='Покупайте продукцию «Атемарской Фермы», регистрируйте чеки и выигрывайте призы: сертификаты Ozon, аэрогрили и холодильники', help_text='Используется, если у страницы не задано своё описание', verbose_name='Описание по умолчанию (description)')),
                ('og_image', models.ImageField(blank=True, help_text='Если не задано — используется картинка по умолчанию из статики', null=True, upload_to='seo/', verbose_name='Изображение для соцсетей (og:image)')),
            ],
            options={
                'verbose_name': 'SEO-настройки',
                'verbose_name_plural': 'SEO-настройки',
            },
        ),
        migrations.CreateModel(
            name='SpecialPrizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Загрузите изображение специального приза', upload_to='special_prizes/', verbose_name='Изображение')),
                ('name', models.CharField(help_text='Краткое название приза', max_length=100, verbose_name='Название приза')),
                ('caption', models.CharField(help_text='Дополнительный текст под изображением', max_length=255, verbose_name='Подпись')),
                ('order', models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем выше в списке', verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Специальный приз',
                'verbose_name_plural': 'Специальные призы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WeekPrizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Загрузите изображение приза недели', upload_to='week_prizes/', verbose_name='Изображение')),
                ('name', models.CharField(help_text='Краткое название приза', max_length=100, verbose_name='Название приза')),
                ('caption', models.CharField(help_text='Дополнительный текст под изображением', max_length=255, verbose_name='Подпись')),
                ('order', models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем выше в списке', verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Еженедельный приз',
                'verbose_name_plural': 'Еженедельные призы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например, "Корочанская 84"', max_length=120, unique=True, verbose_name='Название')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='main.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
    ]
