"""
Django settings for проекта «Купи и выиграй с Атемарской».

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from datetime import date
from pathlib import Path
import os 
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    'SECRET_KEY',
    'django-insecure-af-promo-dev-key-change-me-in-production-9f2k3l4m5n6b7v8c',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# В DEBUG вместо реального запроса в ФНС возвращается тестовый ответ из
# promotion/debug_config.py (см. receipt_fns._fetch_fns_data) — чтобы приём чеков
# можно было проверить локально без интеграции с ФНС. Можно переопределить через .env.
FNS_DISABLED = os.getenv('FNS_DISABLED', 'True' if DEBUG else 'False') == 'True'

# Идёт ли акция. Если False — личный кабинет доступен только суперпользователям
# (администраторам, заведённым через /admin/), кнопка «Личный кабинет» не отображается остальным.
ACTION_STARTED = os.getenv('ACTION_STARTED', 'True') == 'True'

# --- Счётчики и подтверждения прав (бриф, п. 13) ---
# Пока значения пустые, счётчик и мета-тег на страницы не попадают — это
# рабочее состояние до старта, а не забытая настройка.
YANDEX_METRIKA_ID = os.getenv('YANDEX_METRIKA_ID', '')
YANDEX_VERIFICATION = os.getenv('YANDEX_VERIFICATION', '')

# --- Сроки Акции «Купи и выиграй с Атемарской» (бриф, п. 2) ---
# Единственная точка правды в коде — календарь Акции хранится в БД (promotion.Raffle),
# эти значения используются как значения по умолчанию при первичном наполнении
# (seed_promo_calendar) и как нижняя граница даты чека в розыгрышах.
PROMO_START_DATE = os.getenv('PROMO_START_DATE', '2026-10-01')
PROMO_END_DATE = os.getenv('PROMO_END_DATE', '2027-01-10')
# Первый недельный период длиннее календарной недели: Акция стартует в четверг
# 01.10.2026, а первый розыгрыш проходит 14.10.2026 — значит период 1 закрывается
# в воскресенье 11.10.2026 (см. promotion/services/promo_calendar.py).
PROMO_FIRST_WEEK_END_DATE = os.getenv('PROMO_FIRST_WEEK_END_DATE', '2026-10-11')
# День недели еженедельного розыгрыша: 2 — среда (14.10, 21.10, ... 13.01).
PROMO_DRAW_WEEKDAY = int(os.getenv('PROMO_DRAW_WEEKDAY', '2'))
PROMO_MAIN_DRAW_DATE = os.getenv('PROMO_MAIN_DRAW_DATE', '2027-01-13')

# Чеки с датой покупки раньше этой в розыгрышах не участвуют (страховка от
# «чеков из прошлого», см. promotion/services/draw_result.py).
RAFFLE_RECEIPT_MIN_DATE = date.fromisoformat(PROMO_START_DATE)

# Показывать тестовых победителей в блоке "Победители" на лендинге, если в БД
# ещё нет реальных опубликованных итогов розыгрыша. Только для проверки вёрстки.
MOCK_WINNERS = os.getenv('MOCK_WINNERS', 'False') == 'True'

# Ссылка на видео в правой колонке блока hero (S3-хранилище).
HERO_VIDEO_URL = os.getenv('HERO_VIDEO_URL', '')

# Домены Акции (бриф, п. 12): лендинг — af-promo.ru, личный кабинет — af.cheqly.ru.
# Дополнительные хосты (IP сервера, стенды) добавляются через ALLOWED_HOSTS в .env.
ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    'af.cheqly.ru',
    'af-promo.ru',
    'www.af-promo.ru',
    *[h.strip() for h in os.getenv('ALLOWED_HOSTS', '').split(',') if h.strip()],
]

CSRF_TRUSTED_ORIGINS = [
    'https://af.cheqly.ru',
    'https://af-promo.ru',
    'https://www.af-promo.ru',
    *[o.strip() for o in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()],
]

# nginx проксирует по HTTP и передаёт исходную схему в X-Forwarded-Proto — без этой
# настройки request.scheme/is_secure() всегда считали бы запрос по HTTP, из-за чего
# в robots.txt ссылка на sitemap.xml собиралась на http:// вместо https://.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_celery_beat',

    'django.contrib.sitemaps', 

    'promotion',
    'main',
    'staff_panel',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'promotion.middleware.UTMMiddleware',
]

X_FRAME_OPTIONS = 'SAMEORIGIN'

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'main.context_processors.debug_context',
                'main.context_processors.company_info_context',
                'main.context_processors.seo_settings_context',
                'main.context_processors.hero_video_context',
                'promotion.context_processors.cabinet_access_context',
                'promotion.context_processors.win_prize_modal_context',
                'promotion.context_processors.instant_game_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

if DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('POSTGRES_DB', 'atemar'),
            'USER': os.getenv('POSTGRES_USER', 'postgres'),
            'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'atemar_1379!'),
            'HOST': os.getenv('POSTGRES_HOST', 'db'),
            'PORT': os.getenv('POSTGRES_PORT', '5432'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = '/var/www/static'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'promotion.User'

# DaData suggestions API token
DADATA_API_KEY = os.getenv('DADATA_API_KEY', '')

CELERY_BROKER_URL = 'redis://redis:6379/0'
CELERY_RESULT_BACKEND = 'redis://redis:6379/0'

if DEBUG:
    # Локальный Redis в Docker (см. README/локальную разработку) — порт нестандартный,
    # чтобы не конфликтовать с системным Redis на 6379.
    CELERY_BROKER_URL = 'redis://127.0.0.1:38432/0'
    CELERY_RESULT_BACKEND = 'redis://127.0.0.1:38432/0'

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': 'redis://redis:6379/1',
    },
}

if DEBUG:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': 'redis://127.0.0.1:38432/1',
        },
    }

# Сколько файлов Django принимает в одном multipart-запросе. Дефолт Django — 100,
# из-за него массовая загрузка файлов призов (/panel/prize-files/) обрывалась
# раньше собственного лимита MAX_FILES_PER_UPLOAD в staff_panel/services/prize_files.py.
DATA_UPLOAD_MAX_NUMBER_FILES = 300

# Минимальная совокупная стоимость акционных товаров в чеке, рубли.
# Бриф, п. 4: «Минимальная сумма чека — без ограничений», поэтому порога нет —
# чек принимается, если в нём нашлись акционные позиции. Порог включается одной
# строкой (или переменной PROMO_MIN_SUM_RUB в .env), если условие изменится.
PROMO_MIN_SUM_RUB = float(os.getenv('PROMO_MIN_SUM_RUB', '0'))

# Минимальный интервал между загрузками чеков одним участником (сек.)
RECEIPT_UPLOAD_COOLDOWN_SECONDS = 30
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

LOGIN_URL = 'participants:login'

# Личный кабинет участника (бриф, п. 12). Лендинг живёт на отдельном домене
# af-promo.ru и ссылается сюда — см. LANDING_URL.
SITE_URL = os.getenv('SITE_URL', 'https://af.cheqly.ru')
LANDING_URL = os.getenv('LANDING_URL', 'https://af-promo.ru')
SUPPORT_EMAIL = os.getenv('SUPPORT_EMAIL', 'af@cheqly.ru')

# --- Уведомления в отдельный Telegram-бот (по примеру FarPostBot, без server_name) ---
# Напоминания за сутки до розыгрышей + уведомления обо всех проблемах (включая
# Cyclops: нехватка средств и любые другие ошибки). См. promotion/services/notify_bot.py
FORWARD_SIGNAL_URL = os.getenv('FORWARD_SIGNAL_URL', 'https://forward-signal.ru/api/send/')
NOTIFY_API_TIMEOUT = int(os.getenv('NOTIFY_API_TIMEOUT', '30'))
NOTIFY_MAX_RETRIES = int(os.getenv('NOTIFY_MAX_RETRIES', '3'))
NOTIFY_RETRY_DELAY = int(os.getenv('NOTIFY_RETRY_DELAY', '10'))

# --- OpenRouter: проверка чеков нейросетью (promotion/services/v2_validate_receipt) ---
# Модель задаётся слагом OpenRouter. Пустой OPENROUTER_API_KEY — штатный рубильник:
# нейросеть не вызывается, чеки без совпадения по ключевым словам просто уходят на
# ручную модерацию, как было до её подключения.
# Модель с суффиксом ":free" бесплатна, но ограничена 50 запросами в сутки на весь
# аккаунт (1000 — после пополнения баланса на $10). Платная qwen/qwen3.8-flash стоит
# около копейки за чек и лимитов не имеет — переключение на неё это одна строка здесь.
OPENROUTER_API_KEY = os.getenv('OPENROUTER_API_KEY', '')
OPENROUTER_MODEL = os.getenv('OPENROUTER_MODEL', 'qwen/qwen3.8-flash')
OPENROUTER_TIMEOUT = int(os.getenv('OPENROUTER_TIMEOUT', '30'))

# Теневой режим: нейросеть получает те же чеки и в тех же ситуациях, что и в бою,
# но её ответ ни на что не влияет — ни на статус чека, ни на системное сообщение,
# ни на ключевые слова. Разбор складывается в поля чека (ai_recommendation,
# ai_review_note, ai_reviewed_at), чтобы оценить её работу на реальном объёме
# перед тем, как отдавать ей право решать.
OPENROUTER_SHADOW_MODE = os.getenv('OPENROUTER_SHADOW_MODE', 'True') == 'True'

# --- OkiDoki: договоры с победителями ---
# callback_url вшивается в каждый договор в момент его создания и потом не
# меняется, поэтому он обязан указывать на боевой домен именно этого проекта.
# До 09.2026 здесь не было ничего, и в promotion/services/oki_doki.py срабатывал
# фолбэк с доменом другого проекта: OkiDoki честно слал
# callback'и туда, наш /oki-doki/callback/ не получал ничего, и статусы
# договоров навсегда застревали на «Выставлен». Страховка от повторения —
# ежедневная сверка (promotion/services/oki_status_sync.py).
OKI_DOKI_API_KEY = os.getenv('OKI_DOKI_API_KEY', '')
OKI_DOKI_CALLBACK_URL = os.getenv('OKI_DOKI_CALLBACK_URL', f'{SITE_URL}/oki-doki/callback/')

# Статусы OkiDoki для monitor_oki_documents (подстрока, без учёта регистра)
OKI_STATUS_AWAITING_CUSTOMER = (
    'черновик',
    'ожидает проверки',
    'ожидает проверку',
)
OKI_STATUS_AWAITING_PARTICIPANT = (
    'выставлен',
    'ожидает подписи',
    'ожидает подпись',
    'ожидается подпись'
)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'django_errors.log',
        },
        'notify_bot': {
            'level': 'ERROR',
            'class': 'promotion.services.notify_bot.TelegramNotifyLogHandler',
        },
    },
    'root': {
        # В DEBUG уведомления в Telegram отключены — иначе локальные ошибки
        # (например DisallowedHost от случайных запросов на dev-сервер) летят в бот.
        'handlers': ['file'] if DEBUG else ['file', 'notify_bot'],
        'level': 'ERROR',
    },
}

# --- Точка Банк Cyclops («Расчёты по номинальному счёту») ---
# Выплата гарантированного приза через СБП. См. docs/cyclops-integration-plan.md
CYCLOPS_CONFIG = {
    # Транспорт и аутентификация
    'BASE_URL': os.getenv('CYCLOPS_BASE_URL', 'https://pre.tochka.com/api/v1/cyclops'),
    'PLATFORM_ID': os.getenv('CYCLOPS_PLATFORM_ID', ''),
    'CERT_THUMBPRINT': os.getenv('CYCLOPS_CERT_THUMBPRINT', ''),
    'PRIVATE_KEY_PATH': os.getenv('CYCLOPS_PRIVATE_KEY_PATH', ''),
    # На pre-слое допустима подпись '12345'; на prod обязательна реальная подпись.
    'USE_TEST_KEY': os.getenv('CYCLOPS_USE_TEST_KEY', 'True') == 'True',
    'NOMINAL_ACCOUNT': os.getenv('CYCLOPS_NOMINAL_ACCOUNT', ''),
    # Реквизиты банка номинального счёта — для автогенерации Договора присоединения
    # к Оферте (contract_offer), раздел «Номинальный счёт». Дефолты — реквизиты
    # ООО «БАНК ТОЧКА» из согласованной Оферты № 2508/2026/1.
    'NOMINAL_BANK_NAME': os.getenv('CYCLOPS_NOMINAL_BANK_NAME', 'ООО «БАНК ТОЧКА» г. Москва'),
    'NOMINAL_BANK_BIC': os.getenv('CYCLOPS_NOMINAL_BANK_BIC', '044525104'),
    'NOMINAL_BANK_CORR_ACCOUNT': os.getenv('CYCLOPS_NOMINAL_BANK_CORR_ACCOUNT', '30101810745374525104'),

    # Плательщик призового фонда (бенефициар + виртуальный счёт) хранится в БД —
    # синглтон promotion.models.CyclopsSettings, настраивается через интерфейс.

    # Параметры выплаты денежного приза
    'PRIZE_AMOUNT': float(os.getenv('CYCLOPS_PRIZE_AMOUNT', '50')),
    'PRIZE_PURPOSE': os.getenv('CYCLOPS_PRIZE_PURPOSE', 'Гарантированный приз, без НДС'),
    # Необязательный запасной путь к шаблону service_agreement (приоритет — у файла из настроек)
    'SERVICE_AGREEMENT_PDF': os.getenv('CYCLOPS_SERVICE_AGREEMENT_PDF', ''),

    # Число попыток выплаты в Celery-ретраях
    'MAX_PAYOUT_RETRIES': int(os.getenv('CYCLOPS_MAX_PAYOUT_RETRIES', '2')),

    # Пауза между отправками выплат при плановой пакетной рассылке (сек.) —
    # чтобы не отправлять в Точку Банк десятки/сотни запросов одновременно.
    'PAYOUT_THROTTLE_SECONDS': int(os.getenv('CYCLOPS_PAYOUT_THROTTLE_SECONDS', '5')),

    # БИКи банков, которые временно исключаются из плановой выплаты (участники
    # с таким БИК остаются в «Отложена», не помечаются ошибкой) — например,
    # банк не резолвится в справочнике СБП и решение по нему ещё не принято
    # с Заказчиком. Список через запятую в CYCLOPS_BLOCKED_BANK_BIKS.
    'BLOCKED_BANK_BIKS': {
        bik.strip() for bik in os.getenv('CYCLOPS_BLOCKED_BANK_BIKS', '').split(',') if bik.strip()
    },

    # Плановая пакетная выплата раз в неделю по пятницам. Пока False расписание
    # вообще не регистрируется в Celery beat (см. config/celery.py), а сама
    # задача при вызове сразу выходит — выплаты идут только вручную из панели
    # или админки. Включать осознанно, после контрольной выплаты на проде.
    'SCHEDULED_PAYOUTS_ENABLED': os.getenv('CYCLOPS_SCHEDULED_PAYOUTS_ENABLED', 'False') == 'True',
}


# --- Моментальные призы («лоток яиц») ---
# Механика: за каждый принятый чек участник получает попытку открыть одно из
# десяти яиц. Внутри яйца либо приз, либо пусто. Выигрыш определяется призовыми
# моментами (promotion.models.InstantMoment) — заранее сгенерированным
# расписанием, равномерно размазанным по всей Акции, чтобы призы уходили
# примерно поровну каждый день. Подробности — promotion/services/instant_prizes.py.
INSTANT_PRIZES = {
    # Сколько яиц показывается в лотке. Выбор яйца — оформление: исход попытки
    # определяется сервером в момент клика, а не заранее «спрятан» в ячейке.
    'EGGS_PER_TRAY': int(os.getenv('INSTANT_EGGS_PER_TRAY', '10')),
    # Сколько попыток даёт один принятый чек.
    'ATTEMPTS_PER_RECEIPT': int(os.getenv('INSTANT_ATTEMPTS_PER_RECEIPT', '1')),
    # Часы суток, внутри которых раскладываются призовые моменты. Ночью призы
    # не «сгорают» впустую: момент, до которого никто не доиграл, остаётся
    # доступным и достаётся первому же игроку после его наступления.
    'DAY_START_HOUR': int(os.getenv('INSTANT_DAY_START_HOUR', '8')),
    'DAY_END_HOUR': int(os.getenv('INSTANT_DAY_END_HOUR', '23')),
    # Через сколько часов непойманный призовой момент сгорает. 0 — не сгорает
    # никогда (по умолчанию: призовой фонд должен быть разыгран полностью).
    'MOMENT_TTL_HOURS': int(os.getenv('INSTANT_MOMENT_TTL_HOURS', '0')),
}
